version: "3"

services:
  main_terminal:
    build:
      context: ./main_terminal
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:latest
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1
      - REDIS_DATABASES=0
    ports:
      - "6500:6379"
